# Generated by Django 5.1.4 on 2024-12-31 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hello_app.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
