# Generated by Django 5.1.4 on 2025-01-02 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_customer_phone_number_alter_transaction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction date'),
        ),
    ]
