# Generated by Django 5.1.4 on 2025-01-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_transaction_transaction_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='DEF', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='DEF', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='DEF', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='DEFZIP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='DEFSTATE', max_length=50),
            preserve_default=False,
        ),
    ]
