# Generated by Django 5.1.4 on 2025-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
    ]
