# Generated by Django 5.1.4 on 2024-12-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.IntegerField(),
        ),
    ]
